[package]
name = "formatter"
version = "0.1.0"
authors = ["Daniel Wippermann <Daniel.Wippermann@gmail.com>"]
edition = "2021"

[dependencies]
clap = "2.20"
env_logger = "0.4"
log = "0.3"
"resol-vbus" = { path = "../.." }
