name: Rust

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Bootstrap
      run: |
        wget https://github.com/mozilla/grcov/releases/download/v0.8.7/grcov-x86_64-unknown-linux-gnu.tar.bz2
        tar xjf grcov-x86_64-unknown-linux-gnu.tar.bz2
        rustup component add llvm-tools-preview
    - name: Test
      run: RUSTFLAGS="-C instrument-coverage" LLVM_PROFILE_FILE="profile.profraw" cargo test --lib
    - name: Coverage
      run: |
        ./grcov . -s . --binary-path ./target/debug/ -t lcov --branch --ignore-not-existing --ignore "/home/runner/.cargo/registry/src/**/*" -o ./lcov.info
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        files: ./lcov.info
        flags: unittests
        fail_ci_if_error: true
        verbose: true
